#!/bin/bash
# Setup WhatsApp notification for Valentine response
# This script helps you set up automatic WhatsApp forwarding

echo "🎯 Valentine WhatsApp Notification Setup"
echo "========================================"
echo ""

echo "Option 1: Phone Notification (Instant)"
echo "--------------------------------------"
echo "1. Install ntfy app on your phone"
echo "   iOS: https://apps.apple.com/app/ntfy/id1625396347"
echo "   Android: https://play.google.com/store/apps/details?id=io.heckel.ntfy"
echo ""
echo "2. Open the app and subscribe to:"
echo "   Topic: praise-valentine-4her"
echo ""
echo "3. Done! You'll get instant notification when she clicks 'Yes'"
echo ""
echo "========================================"
echo ""

echo "Option 2: WhatsApp Auto-Forward (via Clawdbot)"
echo "--------------------------------------"
echo "Run this in your terminal:"
echo ""
echo "# Monitor ntfy.sh and forward to WhatsApp"
echo "while true; do"
echo "  curl -s https://ntfy.sh/praise-valentine-4her/json | \\"
echo "  grep -q 'SHE SAID YES' && \\"
echo "  clawdbot message send --to=+9898540352 --message='💜 Adufe said YES to being your Valentine! 🎉'"
echo "  sleep 5"
echo "done"
echo ""
echo "========================================"
echo ""

echo "Current Status:"
echo "✅ Website configured to send to ntfy.sh"
echo "✅ Topic: praise-valentine-4her"
echo "✅ Notification URL: https://ntfy.sh/praise-valentine-4her"
echo ""
echo "Test the notification:"
echo "curl -d '🧪 Test notification' https://ntfy.sh/praise-valentine-4her"
